version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: WordToPhrase_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_TABLE}
    ports:
        - "9812:5432"