spring:
  datasource:
      url: jdbc:postgresql://localhost:9812/${DB_TABLE}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: WordToPhrase
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

  mail:
    host: ${MAIL_SERVER}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true